/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QueryDeskRouteImport } from './routes/query-desk'
import { Route as BrochureRouteImport } from './routes/brochure'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryDeskRoute = QueryDeskRouteImport.update({
  id: '/query-desk',
  path: '/query-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochureRoute = BrochureRouteImport.update({
  id: '/brochure',
  path: '/brochure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brochure': typeof BrochureRoute
  '/query-desk': typeof QueryDeskRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brochure': typeof BrochureRoute
  '/query-desk': typeof QueryDeskRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brochure': typeof BrochureRoute
  '/query-desk': typeof QueryDeskRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brochure' | '/query-desk' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brochure' | '/query-desk' | '/register'
  id: '__root__' | '/' | '/brochure' | '/query-desk' | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrochureRoute: typeof BrochureRoute
  QueryDeskRoute: typeof QueryDeskRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query-desk': {
      id: '/query-desk'
      path: '/query-desk'
      fullPath: '/query-desk'
      preLoaderRoute: typeof QueryDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochure': {
      id: '/brochure'
      path: '/brochure'
      fullPath: '/brochure'
      preLoaderRoute: typeof BrochureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrochureRoute: BrochureRoute,
  QueryDeskRoute: QueryDeskRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
